// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.team1277.robot;
    
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.GearTooth;
import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.livewindow.LiveWindowSendable;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftMotor;
    public static SpeedController driveTrainRightMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static Gyro gyro;
    
    public static GearTooth gearToothLeft;
    public static GearTooth gearToothRight;
    
    public static DigitalInput limitSwitchTop;
    public static DigitalInput limitSwitchBottom;
    public static Relay lift;
    
    public static SpeedController wheelArmMove;
    public static Relay wheelArmLeft;
    public static Relay wheelArmRight;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftMotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "leftMotor", (Talon) driveTrainLeftMotor);
        
        driveTrainRightMotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "rightMotor", (Talon) driveTrainRightMotor);
        
       
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        gyro = new Gyro(0); //TODO: change port
        LiveWindow.addSensor("DriveTrain", "gyro", gyro);
        gearToothLeft = new GearTooth(7);
        LiveWindow.addSensor("DriveTrain", "leftSensor", gearToothLeft);
        gearToothRight = new GearTooth(6);
        LiveWindow.addSensor("DriveTrain", "rightSensor", gearToothRight);
        
        lift = new Relay(0);
        LiveWindow.addActuator("Lift", "liftRelay", lift);
        
        wheelArmMove = new Talon(3);
        LiveWindow.addActuator("WheelArms", "wheelArmMove", (Talon) wheelArmMove);
        wheelArmLeft = new Relay(1);
        LiveWindow.addActuator("WheelArms", "wheelArmLeftSpin", wheelArmLeft);
        wheelArmRight = new Relay(2);
        LiveWindow.addActuator("WheelArms", "wheelArmRightSpin", wheelArmRight);
        
        limitSwitchTop = new DigitalInput(8);
        LiveWindow.addSensor("Lift", "topLimitSwitch", limitSwitchTop);
        limitSwitchBottom = new DigitalInput(9);
        LiveWindow.addSensor("Lift", "bottomLimitSwitch", limitSwitchBottom);        
    }
}
